const action_types = {
    LOGIN_USER: 'LOGIN_USER',
    SIGNUP_CLIENT: 'SIGNUP_CLIENT',
    LOGIN_OWNER: 'LOGIN_OWNER',
    SIGNUP_OWNER: 'SIGNUP_OWNER',
    RESTAURANT_LIST: 'RESTAURANT_LIST',
    DISTINCT_CUISINES: 'DISTINCT_CUISINES',
    SEARCH_ITEM: 'SEARCH_ITEM',
    MENU_ITEMS: 'MENU_ITEMS',
    MENU_SECTIONS: 'MENU_SECTIONS',
    ADD_TO_CART:  'ADD_TO_CART',
}

export default action_types;